"""Stage 6b — Report (tech spec §6).

Writes ``metrics.json`` (machine-readable, schema per §6) and a human-readable
markdown summary. Plotting is intentionally decoupled and lives behind the
``cv`` extra (matplotlib); it is skipped when unavailable.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path

from .metrics import MetricsReport
from .models import Timelines, VideoMeta


def build_report(
    meta: VideoMeta,
    timelines: Timelines,
    metrics: MetricsReport,
    n_tracks: int,
    count_estimate: int,
) -> dict[str, object]:
    """Assemble the full report dict matching the §6 schema."""
    return {
        "video": {
            "path": meta.path,
            "fps": meta.fps,
            "duration_s": round(meta.duration_s, 2),
            "resolution": [meta.width, meta.height],
        },
        "props": {"count_estimate": count_estimate, "tracks": n_tracks},
        "events": {
            "throws": [asdict(e) | {"hand": e.hand.value} for e in timelines.throws],
            "catches": [asdict(e) | {"hand": e.hand.value} for e in timelines.catches],
            "drops": [asdict(e) for e in timelines.drops],
        },
        "metrics": metrics.to_dict(),
    }


def write_json(report: dict[str, object], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "metrics.json"
    path.write_text(json.dumps(report, indent=2))
    return path


def write_markdown(report: dict[str, object], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "summary.md"
    path.write_text(_render_markdown(report))
    return path


def _render_markdown(report: dict[str, object]) -> str:
    video = report["video"]
    props = report["props"]
    metrics = report["metrics"]
    assert isinstance(video, dict)
    assert isinstance(props, dict)
    assert isinstance(metrics, dict)

    rhythm = metrics["rhythm"]
    spatial = metrics["spatial"]
    symmetry = metrics["symmetry"]
    failure = metrics["failure"]
    scores = metrics["scores"]

    lines = [
        "# Superjuggling — Consistency Report",
        "",
        f"**Clip:** `{video['path']}`  ",
        f"**Duration:** {video['duration_s']} s · "
        f"**fps:** {video['fps']} · "
        f"**resolution:** {video['resolution'][0]}×{video['resolution'][1]}  ",
        f"**Props (estimate):** {props['count_estimate']} · "
        f"**tracks:** {props['tracks']}",
        "",
        f"## Overall consistency: **{metrics['overall_consistency']} / 100**",
        "",
        "| Domain | Score |",
        "|---|---|",
        f"| Rhythm | {scores['rhythm']} |",
        f"| Spatial | {scores['spatial']} |",
        f"| Symmetry | {scores['symmetry']} |",
        f"| Failure | {scores['failure']} |",
        "",
        "### Rhythm (§5.1)",
        f"- Cadence: **{rhythm['cadence_hz']} Hz**",
        f"- Inter-throw-interval CV: {rhythm['iti_cv']}",
        f"- Hand-dwell CV: {rhythm['dwell_cv']}",
        f"- L/R tempo balance: {rhythm['lr_tempo_balance']}",
        "",
        "### Height & placement (§5.2)",
        f"- Throw-height CV: {spatial['height_cv']}",
        f"- Apex-lateral CV: {spatial['apex_lateral_cv']}",
        f"- Pattern width: {spatial['pattern_width_px']} px",
        f"- Envelope drift: {spatial['envelope_drift']}",
        f"- Height/cadence coherence: {spatial['height_cadence_coherence']}",
        "",
        "### Symmetry (§5.3)",
        f"- L/R height symmetry: {symmetry['lr_height_symmetry']}",
        f"- L/R placement symmetry: {symmetry['lr_placement_symmetry']}",
        f"- Throw balance (L fraction): {symmetry['throw_balance']}",
        "",
        "### Failure & endurance (§5.4)",
        f"- Drops: {failure['drops']} ({failure['drop_rate_per_min']} / min)",
        f"- Longest clean run: {failure['longest_clean_run_s']} s",
        f"- Recovery time: {failure['recovery_s']} s",
        "",
        "_Generated by superjuggling (draft)._",
    ]
    return "\n".join(lines)


def write_report(
    meta: VideoMeta,
    timelines: Timelines,
    metrics: MetricsReport,
    out_dir: Path,
    n_tracks: int,
    count_estimate: int,
) -> dict[str, Path]:
    """Write JSON + markdown and return the paths."""
    report = build_report(meta, timelines, metrics, n_tracks, count_estimate)
    return {
        "json": write_json(report, out_dir),
        "markdown": write_markdown(report, out_dir),
    }
